# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
env:
    CHROME_PROPERTIES: "chrome.properties"
    WITH_PARAMS: "-ntp -Ddriver=chrome -Dchrome.capabilities.path=$CHROME_PROPERTIES"
    UNIT: "-Punit"
    COMMON: "-Pcommon"
    COMPLEX: "-Pcomplex"
    GROUP_ID: "com.epam.jdi"
    NOPO_TESTS: "jdi-bdd-no-po-tests"
    NOPO_TESTS_PROPERTY: "test-examples/jdi-bdd-no-po-tests"
    BDD_TESTS: "jdi-bdd-tests"
    BOOTSTRAP_TESTS: "jdi-light-bootstrap-tests"
    HTML_TESTS: "jdi-light-html-tests"
    ANGULAR_TESTS: "jdi-light-angular-tests"
    ANGULAR_TESTS_WITH_MOCKS: "jdi-light-angular-tests-with-mocks"
    EXAMPLES: "jdi-light-examples"
    EXAMPLES_PROPERTY: "test-examples/jdi-light-examples"
    PERFORMANCE: "jdi-performance"
    PERFORMANCE_PROPERTY: "test-examples/jdi-performance"
    CHROME_ARGS: "--no-sandbox --headless --disable-dev-shm-usage --disable-gpu --window-size=1920,1080"

on:
  push:
    branches: [ test_ga ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        java-package: jdk
    - name: Install Chomium
      run: sudo apt-get install chromium-browser

    - name: Prepare environment
      run: |
        java -Xmx32m -version
        ls -lah
        google-chrome --version
        env
        id

          
    - name: Welcome to JDI
      run: |
        echo ------------------- WELCOME TO JDI -----------------------
        mvn --version

    - name: Compile jdi code
      run: mvn -ntp install -DskipTests

    - name: Tests BDD
      run: |
        echo arguments=$CHROME_ARGS > "./$BDD_TESTS/src/test/resources/$CHROME_PROPERTIES"
        google-chrome --headless --disable-gpu --dump-dom https://jdi-testing.github.io/jdi-light/index.html
        free
        df -a
        mvn verify $WITH_PARAMS -pl $GROUP_ID:$BDD_TESTS

    - name: PS list
      if: ${{ always() }}
      run: ps -aux
    
    # - name: Tests bootstrap
    #   run: |
    #       mvn -ntp install -DskipTests
    #       echo arguments=$CHROME_ARGS > "./$BOOTSTRAP_TESTS/src/test/resources/$CHROME_PROPERTIES"
    #       mvn verify $WITH_PARAMS -pl $GROUP_ID:$BOOTSTRAP_TESTS

    # - name: Run tests - angular unit tests
    #   run: | 
    #       mvn -ntp install -DskipTests
    #       echo arguments=$CHROME_ARGS > "./$ANGULAR_TESTS/src/test/resources/$CHROME_PROPERTIES"
    #       mvn verify $WITH_PARAMS $UNIT -pl $GROUP_ID:$ANGULAR_TESTS